### PR TITLE
feat: Drop py3.7 

### PR DESCRIPTION
**Pull request by astuyve**
…e ago

### What does this PR do?
Python 3.7 is now in [phase 1 deprecation](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html), so we do not plan on releasing new features or fixes as there is no continued security or technical support from AWS, and we cannot create new 3.7 functions.

### Types of Changes

- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Misc (docs, refactoring, dependency upgrade, etc.)

### Check all that apply

- [ ] This PR's description is comprehensive
- [ ] This PR contains breaking changes that are documented in the description
- [ ] This PR introduces new APIs or parameters that are documented and unlikely to change in the foreseeable future
- [ ] This PR impacts documentation, and it has been updated (or a ticket has been logged)
- [ ] This PR's changes are covered by the automated tests
- [ ] This PR collects user input/sensitive content into Datadog
- [ ] This PR passes the integration tests (ask a Datadog member to run the tests)

### CODE REVIEW

**Comment by duncanista** [comment]
Looks good, nit:
https://github.com/DataDog/datadog-lambda-python/blob/8e74ac2e0d7f4071eacf6caa7b981d3adf1e226c/datadog_lambda/cold_start.py#L149

Do we need too change something here?

**Comment by duncanista** [comment]
Another nit:
https://github.com/DataDog/datadog-lambda-python/blob/8e74ac2e0d7f4071eacf6caa7b981d3adf1e226c/CONTRIBUTING.md#L27

Maybe we can change this too?

**Review by duncanista — APPROVED** [review]
LGTM!

**Comment by astuyve** [comment]
> Looks good, nit:
> 
> https://github.com/DataDog/datadog-lambda-python/blob/8e74ac2e0d7f4071eacf6caa7b981d3adf1e226c/datadog_lambda/cold_start.py#L149
> 
> Do we need too change something here?

I debated this. With the poetry changes, users shouldn't be able to manually include this library in py3.7 functions so it's probably fine. Will remove

**Review by purple4reina — APPROVED** [review]

**Pull request merged**
