### PR TITLE
Do not include instrumentation for test runners.

### PR DESCRIPTION
**Pull request by purple4reina**
### What does this PR do?

Removes the following instrumentation libraries from ddtrace:
+ `pytest`
+ `pytest_bdd`
+ `pytest_benchmark`
+ `unittest`
+ `coverage`

### Motivation

Reduces size of the layer.

Before
```
Layer file .layers/datadog_lambda_py-amd64-3.9.zip has zipped size 3480 kb
Layer file .layers/datadog_lambda_py-amd64-3.9.zip has unzipped size 10485 kb
```

After
```
Layer file .layers/datadog_lambda_py-amd64-3.9.zip has zipped size 3452 kb
Layer file .layers/datadog_lambda_py-amd64-3.9.zip has unzipped size 10393 kb
```

### Additional Notes

These packages are only necessary if customers are running their python tests in lambda and have enabled the testing ci tools. If they are doing this and still want these instrumentations, then they can always vendor their own version of ddtrace.

### Types of Changes

- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Misc (docs, refactoring, dependency upgrade, etc.)

### Check all that apply

- [ ] This PR's description is comprehensive
- [ ] This PR contains breaking changes that are documented in the description
- [ ] This PR introduces new APIs or parameters that are documented and unlikely to change in the foreseeable future
- [ ] This PR impacts documentation, and it has been updated (or a ticket has been logged)
- [ ] This PR's changes are covered by the automated tests
- [ ] This PR collects user input/sensitive content into Datadog
- [ ] This PR passes the integration tests (ask a Datadog member to run the tests)

https://datadoghq.atlassian.net/browse/SVLS-4701

### CODE REVIEW

**Comment by duncanista** [comment]
Although I like the idea – wouldn't this be technically a breaking change?

**Comment by purple4reina** [comment]
> Although I like the idea – wouldn't this be technically a breaking change?

Yeah. It would be a breaking change. We'd need to add this to the release notes to make sure customers are aware of it.

Given that the size decrease isn't huge (about 30mb compressed) I think it's worth considering if we should do this at all.

**Comment by joeyzhao2018** [comment]
Are those the only things we can strip from `ddtrace.contrib`? I'm thinking if we are doing this (breaking change) let's get them all! WDYT?

**Comment by purple4reina** [comment]
Closing this for now since the size impact isn't that noticeable. We can revisit later if we need to claw 28 kb back.

**Pull request closed without merging**
