### PR TITLE
fix hello route hit too early

### PR DESCRIPTION
**Pull request by maxday**
### What does this PR do?

Call the /hello route at the right moment

### Motivation

Consistency in metric tagging with the extension

### Testing Guidelines

With integration testing

### Types of Changes

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Misc (docs, refactoring, dependency upgrade, etc.)

### Check all that apply

- [x] This PR's description is comprehensive
- [ ] This PR contains breaking changes that are documented in the description
- [ ] This PR introduces new APIs or parameters that are documented and unlikely to change in the foreseeable future
- [ ] This PR impacts documentation, and it has been updated (or a ticket has been logged)
- [x] This PR's changes are covered by the automated tests
- [ ] This PR collects user input/sensitive content into Datadog
- [x] This PR passes the integration tests (ask a Datadog member to run the tests)

### CODE REVIEW

**Comment by nhinsch** [comment]
Would you mind explaining the old behavior, why it was wrong, and what the new behavior is? From the diff, I couldn't quite follow how this changed the timing of the `/hello` route.

**Comment by maxday** [comment]
Sure !
Old behaviour : the code responsible to call the `hello` route was located of the root of the metry.py. So as soon as this file gets imported, the code executes. This file is imported in wrapper.py so the code will be executed before the actual invocation. This results in hitting the /hello route before setting the extra tags since tags extraction is done once we received the actual invocation.
New behaviour : the code is within a dedicated function which is triggered after that we have notified the extension of an invocation event, so the extension can set the tag properly and metrics sent from the layer to the extension can be properly enhanced with extra tags.

**Review by nhinsch — APPROVED** [review]
LGTM
Is this possible to test in the library, or will we rely on integration tests for this?

**Comment by maxday** [comment]
I think integration tests is a good fit for this one as there are already some unit tests on this part

**Comment by yury-sannikov** [comment]
Well, it seems it's breaking tons of code.

**Pull request merged**
